config/routes.rb
Rails.application.routes.draw do

  resources :histories
  root 'wards#index'

  resources :wards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :ward
end

app/models/ward.rb
class Ward < ApplicationRecord

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:ward_id, :title, :summary, :post, :publication)
    end
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:show, :edit, :update, :destroy]

  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to @ward, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ward_id %>
    <%= form.text_field :ward_id, id: :history_ward_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :history_title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary, id: :history_summary %>
  </div>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_field :post, id: :history_post %>
  </div>

  <div class="field">
    <%= form.label :publication %>
    <%= form.text_field :publication, id: :history_publication %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Ward</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Post</th>
      <th>Publication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.ward %></td>
        <td><%= history.title %></td>
        <td><%= history.summary %></td>
        <td><%= history.post %></td>
        <td><%= history.publication %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ward:</strong>
  <%= @history.ward %>
</p>

<p>
  <strong>Title:</strong>
  <%= @history.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @history.summary %>
</p>

<p>
  <strong>Post:</strong>
  <%= @history.post %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @history.publication %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LDS Ward</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab" rel="stylesheet">
  </head>

  <body>
    <div id="menu">
      <div class="container">
        <h4 id="logo">LDS Ward</h4>
      </div>
    </div>

    <%= yield %>

    <div id="footer">
      <div class="container">
        <p>© 2017 LDS Ward foi criado por Bruno Duarte.</p>
      </div>
    </div>
  </body>
</html>

app/views/wards/_form.html.erb
<%= form_with(model: ward, local: true) do |form| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
      <% ward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ward_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Show', @ward %> |
<%= link_to 'Back', wards_path %>

app/views/wards/index.html.erb
<div class="titleHeader">
  <div class="container">
    <h1>Ward</h1>
    <h5>Mandaremus de varias offendit.</h5>
  </div>
</div>

<div class="container">

  <br>

  <p id="notice"><%= notice %></p>

  <ul class="list_box">
    <li><span>Alas cadastradas no sistema</span></li>

    <% if @wards.count == 0 %>
      <li><span>Nenhuma ala encontrada</span></li>
    <% end %>

    <% @wards.each do |ward| %>
      <li>
        <span><%= ward.name %></span>
        <%= link_to raw('<i class="fa fa-trash" aria-hidden="true"></i>Destroy'), ward, method: :delete, data: { confirm: 'Are you sure?' }, class: 'float_right icon_link' %>
        <%= link_to raw('<i class="fa fa-pencil" aria-hidden="true"></i>Edit'), edit_ward_path(ward), class: 'float_right icon_link' %>
        <%= link_to raw('<i class="fa fa-info" aria-hidden="true"></i>Show'), ward, class: 'float_right icon_link' %>
      </li>
    <% end %>
    <li><%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i>New Ward'), new_ward_path, class: 'icon_link' %></li>
  </ul>

</div>

app/views/wards/new.html.erb
<h1>New Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Back', wards_path %>

app/views/wards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ward.name %>
</p>

<%= link_to 'Edit', edit_ward_path(@ward) %> |
<%= link_to 'Back', wards_path %>